# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 14:41
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(choices=[('pyfun1', 'Python Fundamentals 1'), ('pyfun2', 'Python Fundamentals 2'), ('pyoop', 'Python OOP'), ('flask1', 'Flask Fundamentals'), ('mysql', 'MySQL'), ('django', 'Django')], max_length=45)),
                ('status', models.CharField(choices=[('a', 'assignments'), ('b', 'plans'), ('c', 'commit'), ('d', 'current'), ('e', 'done'), ('f', 'display')], default='a', max_length=45)),
                ('title', models.CharField(max_length=45)),
                ('pageid', models.CharField(max_length=45)),
                ('optional', models.BooleanField(default=False)),
                ('base_points', models.IntegerField()),
                ('time_mult', models.DecimalField(decimal_places=1, max_digits=3)),
                ('est_duration', models.DurationField()),
                ('potential', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('act_duration', models.DurationField(default=datetime.timedelta(0))),
                ('on_time', models.BooleanField(default=False)),
                ('actual', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('c', 'commit'), ('d', 'current'), ('e', 'done'), ('f', 'display')], max_length=45)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scorecard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potential', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('start', models.DateTimeField(blank=True, default=None, null=True)),
                ('end', models.DateTimeField(blank=True, default=None, null=True)),
                ('duration', models.DurationField(default=datetime.timedelta(0))),
                ('on_time', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='scorecard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='dashboard.Scorecard'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
