# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 21:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorecard',
            name='challenge',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
