# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecard',
            name='actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='potential',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
