# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 21:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20171024_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='time_est',
            new_name='hrs_est',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='time_taken',
            new_name='hrs_taken',
        ),
        migrations.RenameField(
            model_name='scorecard',
            old_name='time_vs_est',
            new_name='hrs_vs_est',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='pair',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pair_assignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
