# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 22:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20171028_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scorecard',
            old_name='challenge',
            new_name='time_bonus',
        ),
        migrations.AddField(
            model_name='scorecard',
            name='time_challenge',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
