# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 02:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20171024_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='difficulty',
            new_name='points',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='hrs_est',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='hrs_taken',
        ),
        migrations.AddField(
            model_name='assignment',
            name='time_est',
            field=models.CharField(default='1 hr', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='time_pts',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='ttc',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_assignment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='track',
            field=models.CharField(choices=[('a', 'Python Fundamentals'), ('b', 'Python OOP'), ('c', 'Python: Flask')], max_length=45),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='daily_avg',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='hrs_vs_est',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='weekly_avg',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
