# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20171024_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='ttc',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2),
        ),
    ]
