# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20171025_0839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scorecard',
            old_name='todays_actual',
            new_name='actual',
        ),
        migrations.RenameField(
            model_name='scorecard',
            old_name='todays_potential',
            new_name='potential',
        ),
        migrations.AddField(
            model_name='assignment',
            name='end_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('a', 'assignments'), ('b', 'plans'), ('c', 'current'), ('d', 'done'), ('e', 'display')], max_length=45),
        ),
    ]
