# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20171025_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='est_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='potential',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
