# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20171025_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='time_pts',
            new_name='time_mult',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='track',
            field=models.CharField(choices=[('a', 'Python Fundamentals'), ('b', 'Python: Django')], max_length=45),
        ),
    ]
