# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20171025_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='on_time',
            field=models.BooleanField(default=False),
        ),
    ]
