# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 20:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20171025_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 25, 16, 57, 56, 123681)),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('a', 'assignments'), ('b', 'plans'), ('c', 'commit'), ('d', 'current'), ('e', 'done'), ('f', 'display')], max_length=45),
        ),
        migrations.AlterField(
            model_name='scorecard',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
