# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20171022_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(help_text='8 character length', max_length=100),
        ),
    ]
