# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 23:59
from __future__ import unicode_literals

import apps.members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20171022_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=45, validators=[apps.members.models.lenLessThanFive]),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=100, validators=[apps.members.models.lenLessThanEight]),
        ),
        migrations.AlterField(
            model_name='member',
            name='username',
            field=models.CharField(max_length=45, unique=True, validators=[apps.members.models.lenLessThanFive]),
        ),
    ]
