# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_stack',
            field=models.CharField(choices=[('webfun', 'Web Fundamentals'), ('python', 'Python'), ('java', 'Java'), ('mean', 'MEAN')], default='python', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_familiar',
            field=models.BooleanField(default=False),
        ),
    ]
