# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
