# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_familiar',
        ),
    ]
